"""setup

Revision ID: b3363e7c59e4
Revises: 
Create Date: 2026-05-13 00:26:25.648878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3363e7c59e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('jid', sa.String(), nullable=False),
    sa.Column('invite_link', sa.String(), nullable=False),
    sa.Column('total_participants', sa.Integer(), nullable=False),
    sa.CheckConstraint('total_participants > 0 AND total_participants <= 1024', name='check_total_group_participants'),
    sa.PrimaryKeyConstraint('jid'),
    sa.UniqueConstraint('invite_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
